module.exports = {
    blacklistedWords: [
        'faggot',
        'pussy',
        'fuck',
        'bitch',
        'slut',
        'whore',
        'fag',
        'nigger',
        'gay',
        'kanker',
        'homo',
        'retard',
        'f*ck',
        'f#ck',
        'fock',
        'cancer',
        'neger',
        'tyfus',
        'hoer',
        'harry',
        'styles',
        'nigga',
    ],
};